config/routes.rb
Rails3BootstrapDeviseCancan::Application.routes.draw do
  resources :lunches

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  match "preferred" => "lunches#preferred"
  devise_for :users
  resources :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/lunch.rb
class Lunch < ActiveRecord::Base
  attr_accessible :name, :price, :date, :restaurant, :link
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :preferences
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @matches = Lunch.where(:date => Date.today)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lunches }
    end
  end
end

app/controllers/lunches_controller.rb
class LunchesController < ApplicationController
  # GET /lunches
  # GET /lunches.json
  def index
    @matches = []
    @others = []
    @lunches = Lunch.order("date")
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lunches }
    end
  end

  def preferred
    @matches = []
    if user_signed_in? && current_user.preferences
      names = current_user.preferences.split('|')
      names.map! { |x| "%#{x}%" }
      @matches = Lunch.where(:date => Date.today).where{name.like_any names}
    else
      @matches = []
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @matches }
    end
  end

  # GET /lunches/1
  # GET /lunches/1.json
  def show
    @lunch = Lunch.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lunch }
    end
  end

  # GET /lunches/new
  # GET /lunches/new.json
  def new
    @lunch = Lunch.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lunch }
    end
  end

  # GET /lunches/1/edit
  def edit
    @lunch = Lunch.find(params[:id])
  end

  # POST /lunches
  # POST /lunches.json
  def create
    @lunch = Lunch.new(params[:lunch])

    respond_to do |format|
      if @lunch.save
        format.html { redirect_to @lunch, notice: 'Lunch was successfully created.' }
        format.json { render json: @lunch, status: :created, location: @lunch }
      else
        format.html { render action: "new" }
        format.json { render json: @lunch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lunches/1
  # PUT /lunches/1.json
  def update
    @lunch = Lunch.find(params[:id])

    respond_to do |format|
      if @lunch.update_attributes(params[:lunch])
        format.html { redirect_to @lunch, notice: 'Lunch was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lunch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lunches/1
  # DELETE /lunches/1.json
  def destroy
    @lunch = Lunch.find(params[:id])
    @lunch.destroy

    respond_to do |format|
      format.html { redirect_to lunches_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lunches_helper.rb
module LunchesHelper
end

app/views/home/index.html.erb
<h3>Today's menu:</h3>
  <table class="table table-striped table-bordered">
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th class="hidden-phone">Restaurant</th>
    </tr>
  <% @matches.each do |lunch| %>
    <tr>
      <td><a href="<%= lunch.link %>"><%= lunch.name %></a><div class="visible-phone"><i><%= lunch.restaurant %></i></div>
      </td>
      <td><%= number_to_currency(lunch.price, :separator => ",", :delimiter => "", :format => "%n") %></td>
      <td class="hidden-phone"><a href="<%= lunch.link %>"><%= lunch.restaurant %></a></td>
      <td class="location">62.0 25.0</td>
    </tr>
  <% end %>
  </table>
<br />
<script type="text/javascript">
      function calculateDistance(lat1, lon1, lat2, lon2) {
        var R = 6371; // km
        var dLat = (lat2 - lat1).toRad();
        var dLon = (lon2 - lon1).toRad(); 
        var a = Math.sin(dLat / 2) * Math.sin(dLat / 2) +
                Math.cos(lat1.toRad()) * Math.cos(lat2.toRad()) * 
                Math.sin(dLon / 2) * Math.sin(dLon / 2); 
        var c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a)); 
        var d = R * c;
        return Math.round( d*10 ) / 10;
      }
      Number.prototype.toRad = function() {
        return this * Math.PI / 180;
      }

      var latitude = 62.0;
      var longitude = 25.0;
      var startPos;
      if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(function(position) {
          startPos = position;
//          alert(calculateDistance(startPos.coords.latitude, startPos.coords.longitude, latitude, longitude));
          $('.location').each(function(i,row) {
//              alert(row.innerHTML);
          });
        });
      }
</script>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Lunch", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Today', root_path %>
    </li>
    <li>
    <%= link_to 'This week', lunches_path %>
    </li>
    <li>
    <%= link_to 'My lunches', '/preferred' %>
    </li>
    <li>
    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>        
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', new_user_session_path %>  
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Settings', edit_user_registration_path %>
    </li>
    <% if current_user.has_role? :admin %>
      <li>
      <%= link_to 'Admin', users_path %>
      </li>
    <% end %>
  <% else %>
    <li>
    <%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "What should I eat today?" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails3 Bootstrap Devise Cancan" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-36042188-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
    <a href="https://github.com/Frodotus/Lunch"><img class="hidden-phone" style="z-index:9999; position: absolute; top: 0; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_orange_ff7600.png" alt="Fork me on GitHub"></a>
  </body>
</html>

app/views/lunches/_form.html.erb
<%= simple_form_for(@lunch) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :price %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/lunches/edit.html.erb
<h1>Editing lunch</h1>

<%= render 'form' %>

<%= link_to 'Show', @lunch %> |
<%= link_to 'Back', lunches_path %>

app/views/lunches/index.html.erb
<h3>This weeks menu:</h3>
<% date = Date.today - Date.today.cwday %>
<% (1..7).each do |day| %>
  <table class="table table-striped table-bordered">
  <h4><%= (date + day).strftime('%A') %>:</h4>
  <% day_match = false %>
  <% @matches.each do |lunch| %>
    <% if lunch.date == date + day %>
      <% day_match = true %>
      <tr>
        <td><a href="<%= lunch.link %>"><%= lunch.name %></a><div class="visible-phone"><i><%= lunch.restaurant %></i></div>
        <td><%= number_to_currency(lunch.price, :separator => ",", :delimiter => "", :format => "%n") %></td>
        <td class="hidden-phone"><a href="<%= lunch.link %>"><%= lunch.restaurant %></a></td>
      </tr>
    <% end %>    
  <% end %>
  <% if !day_match %>
    <tr>
      <td>Nothing today...</td>
    </tr>
  <% end %>
  </table>
<% end %>

app/views/lunches/new.html.erb
<h1>New lunch</h1>

<%= render 'form' %>

<%= link_to 'Back', lunches_path %>

app/views/lunches/preferred.html.erb
<h3>Today's menu:</h3>
<% if user_signed_in? %>
  <% if(@matches.size > 0) %>
    <table class="table table-hover table-striped table-bordered">
      <tr>
        <th>Name</th>
        <th>Price</th>
        <th class="hidden-phone">Restaurant</th>
      </tr>
      <% @matches.each do |lunch| %>
      <tr>
        <td><a href="<%= lunch.link %>"><%= lunch.name %></a><div class="visible-phone"><i><%= lunch.restaurant %></i></div>
        <td><%= number_to_currency(lunch.price, :separator => ",", :delimiter => "", :format => "%n") %></td>
        <td class="hidden-phone"><a href="<%= lunch.link %>"><%= lunch.restaurant %></a></td>
      <td class="location">62.0 25.0</td>
      </tr>
      <% end %>
    </table>
  <% else %>
    <h4>How about pizza today?</h4>
    <br />
  <% end %>
<% else %>
<% end %>
<br />

app/views/lunches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @lunch.name %>
</p>

<p>
  <b>Price:</b>
  <%= @lunch.price %>
</p>


<%= link_to 'Edit', edit_lunch_path(@lunch) %> |
<%= link_to 'Back', lunches_path %>

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
  <%= simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Change Role</h3>
    </div>
    <div class="modal-body">
      <%= f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline' %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Change Role", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h3>Users</h3>
<div class="span8">
<table class="table table-condensed">
	  <thead>
      <tr>
          <th>Username</th>
          <th>Email</th>
          <th>Registered</th>
          <th>Role</th>
          <th></th>
          <th></th>                                      
      </tr>
  </thead>   
  <tbody>
  <% @users.each do |user| %>
    <tr>
        <td><%= link_to user.name, user %></td>
        <td><%= user.email %></td>
        <td><%= user.created_at.to_date %></td>
        <td><%= user.roles.first.name.titleize unless user.roles.first.nil? %></td>
        <td>
          <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini" type="button">Change role</a>
          <%= render user %>
        </td>
        <td><%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user %></td>                                       
    </tr>
  <% end %>
  </tbody>
</table>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>